{-# OPTIONS -WnoUnsupportedIndexedMatch #-}
{- Token streams as a term algebra, so that the offside rule becomes a
   syntax-directed judgment on a free model.

   A lexer's output is a list, and a list over `Tok` is the free algebra on
   one sort for the signature `{nilOp, consOp t}`.  Putting the token in the
   *operation* rather than in a second sort is the whole trick, and it is
   the same trick `Annotated/Base` plays with `appOp B`: an operation
   indexed by external data is how a signature carries an annotation.  The
   consequences are exactly the ones that development records --

     * the node cover is by head constructor, so prediction is LL(1) and
       `look` needs no window;
     * `LOp` is infinite, since `consOp` carries a token, and a `Cover`
       does not care;
     * every operation is precise, because a free term algebra is.

   The alternative -- `Theory/Instances/Monoid`, where a string is an
   element of a free monoid -- is the wrong model here even though the data
   is the same.  Layout is not associative in any useful sense: the state
   after a prefix is not a monoid element, and the rule needs to look at
   *the next token*, which the monoid presentation only reaches through a
   lookahead cover.  Cons cells give it for free.

   `V` is `⊥`: token lists are generated by the operations alone, with no
   generators, so the presentation's `gen`/`recGen`/`fβ` obligations are
   all empty.  `noVar` is named rather than written `λ ()` at each use --
   two absurd lambdas are not definitionally equal, and every module in the
   chain must be applied to the *same* one. -}
open import Cubical.Foundations.Prelude
open import Cubical.Foundations.HLevels using (isOfHLevelRetract ; isSet×)
open import Cubical.Categories.Category.Base
open import Cubical.Algebra.Theory.Finitary
open Category
import Cubical.Data.Equality as Eq
open SortedSig
open SortedEqns
module Theory.Instances.Layout.Base where

open import Cubical.Data.Empty using (⊥)
import Cubical.Data.Empty as Empty
open import Cubical.Data.FinData using (Fin ; zero ; suc)
open import Cubical.Data.Nat using (ℕ ; isSetℕ)
open import Cubical.Data.Sigma using (_×_ ; _,_ ; fst ; snd)
open import Cubical.Data.Sum using (_⊎_ ; inl ; inr ; isSet⊎)
open import Cubical.Data.Unit using (Unit ; tt ; isSetUnit)
open import Cubical.Data.W.Indexed using (IW ; node ; isOfHLevelSuc-IW)

-- The alphabet.  Four keywords and an indefinite supply of everything
-- else; only `klet` and `kwhere` are read by the layout rule, and they are
-- distinguished constructors rather than a `Bool` field so that a stream
-- prints legibly in a test.
data TokKind : Type ℓ-zero where
  klet kwhere kin keq : TokKind
  kid : ℕ → TokKind

-- A token is a kind and the column it was found at.  Nothing tracks line
-- numbers: see `Offside`'s header for what that costs.
Tok : Type ℓ-zero
Tok = TokKind × ℕ

private
  kindRep : TokKind → Unit ⊎ (Unit ⊎ (Unit ⊎ (Unit ⊎ ℕ)))
  kindRep klet = inl tt
  kindRep kwhere = inr (inl tt)
  kindRep kin = inr (inr (inl tt))
  kindRep keq = inr (inr (inr (inl tt)))
  kindRep (kid n) = inr (inr (inr (inr n)))

  kindUnrep : Unit ⊎ (Unit ⊎ (Unit ⊎ (Unit ⊎ ℕ))) → TokKind
  kindUnrep (inl _) = klet
  kindUnrep (inr (inl _)) = kwhere
  kindUnrep (inr (inr (inl _))) = kin
  kindUnrep (inr (inr (inr (inl _)))) = keq
  kindUnrep (inr (inr (inr (inr n)))) = kid n

  kindRet : (k : TokKind) → kindUnrep (kindRep k) ≡ k
  kindRet klet = refl
  kindRet kwhere = refl
  kindRet kin = refl
  kindRet keq = refl
  kindRet (kid n) = refl

isSetTokKind : isSet TokKind
isSetTokKind = isOfHLevelRetract 2 kindRep kindUnrep kindRet
  (isSet⊎ isSetUnit (isSet⊎ isSetUnit (isSet⊎ isSetUnit (isSet⊎ isSetUnit isSetℕ))))

isSetTok : isSet Tok
isSetTok = isSet× isSetTokKind isSetℕ

-- The signature.  One sort, so `sortOf` and `resultSort` are constant and
-- every dependency `⊗ᴰ` could express is a dependency on the *index*, not
-- on a sibling slot's value.  That is the shape of a state machine, and it
-- is why the layout judgment fits without any of `Annotated/Linear`'s
-- context-splitting cleverness.
data LSort : Type ℓ-zero where
  str : LSort

data LOp : Type ℓ-zero where
  nilOp : LOp
  consOp : Tok → LOp

Ar : LOp → ℕ
Ar nilOp = 0
Ar (consOp _) = 1

SortOf : (o : LOp) → Fin (Ar o) → LSort
SortOf _ _ = str

LSig : SortedSig LSort ℓ-zero
LSig .ops = LOp
LSig .arity = Ar
LSig .sortOf = SortOf
LSig .resultSort _ = str

LEqns : SortedEqns LSig ℓ-zero
LEqns .eqns = ⊥
LEqns .eqnSort ()
LEqns .varCount ()
LEqns .varSort ()
LEqns .lhs ()
LEqns .rhs ()

private
  opRep : LOp → Unit ⊎ Tok
  opRep nilOp = inl tt
  opRep (consOp t) = inr t

  opUnrep : Unit ⊎ Tok → LOp
  opUnrep (inl _) = nilOp
  opUnrep (inr t) = consOp t

  opRet : (o : LOp) → opUnrep (opRep o) ≡ o
  opRet nilOp = refl
  opRet (consOp t) = refl

isSetLOp : isSet LOp
isSetLOp = isOfHLevelRetract 2 opRep opUnrep opRet (isSet⊎ isSetUnit isSetTok)

private
  srtRep : LSort → Unit
  srtRep str = tt

  srtUnrep : Unit → LSort
  srtUnrep _ = str

  srtRet : (s : LSort) → srtUnrep (srtRep s) ≡ s
  srtRet str = refl

isSetLSort : isSet LSort
isSetLSort = isOfHLevelRetract 2 srtRep srtUnrep srtRet isSetUnit

-- The term model: a plain datatype, so that everything reduces.  A
-- `Cubical.Data.List` of tokens would do just as well mathematically, but
-- a bespoke `data` keeps the operations' equations definitional and keeps
-- the tests `refl`.
data TokList : Type ℓ-zero where
  tnil : TokList
  tcons : Tok → TokList → TokList

Crr : LSort → Type ℓ-zero
Crr str = TokList

private
  Shape : LSort → Type ℓ-zero
  Shape str = LOp

  Pos : (s : LSort) → Shape s → Type ℓ-zero
  Pos str o = Fin (Ar o)

  sortAt : (s : LSort) (sh : Shape s) → Pos s sh → LSort
  sortAt str o a = SortOf o a

  W : LSort → Type ℓ-zero
  W = IW Shape Pos sortAt

  isSetW : (s : LSort) → isSet (W s)
  isSetW = isOfHLevelSuc-IW 1 λ where str → isSetLOp

  toTL : TokList → W str
  toTL tnil = node nilOp λ ()
  toTL (tcons t ts) = node (consOp t) λ _ → toTL ts

  toW : (s : LSort) → Crr s → W s
  toW str = toTL

  fromTL : W str → TokList
  fromTL (node nilOp sub) = tnil
  fromTL (node (consOp t) sub) = tcons t (fromTL (sub zero))

  fromW : (s : LSort) → W s → Crr s
  fromW str = fromTL

  tlRet : (ts : TokList) → fromTL (toTL ts) ≡ ts
  tlRet tnil = refl
  tlRet (tcons t ts) = cong (tcons t) (tlRet ts)

  wRet : (s : LSort) (x : Crr s) → fromW s (toW s x) ≡ x
  wRet str = tlRet

isSetCrr : (s : LSort) → isSet (Crr s)
isSetCrr s = isOfHLevelRetract 2 (toW s) (fromW s) (wRet s) (isSetW s)

-- No generators: the free algebra on nothing is the set of closed terms,
-- which is exactly `TokList`.
noVar : ⊥ → LSort
noVar ()

open import Theory.Free.Base LEqns ⊥ noVar

private
  lOps : Ops {σ = LSig} Crr
  lOps nilOp xs = tnil
  lOps (consOp t) xs = tcons t (xs zero)

  lSat : (e : LEqns .eqns)
    (ρ : (w : vars LEqns e) → Crr (LEqns .varSort e w))
    → TmRec Crr lOps ρ (LEqns .lhs e) ≡ TmRec Crr lOps ρ (LEqns .rhs e)
  lSat () ρ

  LModel : MOD LEqns ℓ-zero .ob
  LModel = (λ s → Crr s , isSetCrr s) , lOps , lSat

module Fold {ℓX} {X : LSort → Type ℓX} (α : Ops {σ = LSig} X) where

  foldTL : TokList → X str
  foldTL tnil = α nilOp λ ()
  foldTL (tcons t ts) = α (consOp t) λ _ → foldTL ts

  fold : (s : LSort) → Crr s → X s
  fold str = foldTL

  foldOp : (o : LOp) (ms : (a : Fin (Ar o)) → Crr (SortOf o a))
    → fold str (lOps o ms) ≡ α o (λ a → fold (SortOf o a) (ms a))
  foldOp nilOp ms = cong (α nilOp) (funExt λ ())
  foldOp (consOp t) ms = cong (α (consOp t)) (funExt λ where zero → refl)

  module _ (f : (s : LSort) → Crr s → X s)
    (homf : (o : LOp) (ms : (a : Fin (Ar o)) → Crr (SortOf o a))
          → f str (lOps o ms) ≡ α o (λ a → f (SortOf o a) (ms a))) where

    foldUniqTL : (ts : TokList) → f str ts ≡ foldTL ts
    foldUniqTL tnil = homf nilOp (λ ()) ∙ cong (α nilOp) (funExt λ ())
    foldUniqTL (tcons t ts) =
        homf (consOp t) (λ _ → ts)
      ∙ cong (α (consOp t)) (funExt λ where zero → foldUniqTL ts)

    foldUniq : (s : LSort) (m : Crr s) → f s m ≡ fold s m
    foldUniq str = foldUniqTL

lPresentation : FreePresentation ℓ-zero
lPresentation .P = LModel
lPresentation .satStrict () ρ
lPresentation .gen ()
lPresentation .rec {X = X} isSetX α sat ρ {s} = Fold.fold {X = X} α s
lPresentation .recGen isSetX α sat ρ ()
lPresentation .recOp {X = X} isSetX α sat ρ = Fold.foldOp {X = X} α
lPresentation .recUniq {X = X} isSetX α sat ρ f homf fβ {s} =
  Fold.foldUniq {X = X} α f homf s
